# Programa de ejemplo de Julia con varios elementos sintácticos

## Comentarios

In [1]:
# Autor: Santiago Pinto                Fecha: 2024-06-09
# Estos son comentarios de una línea, comienzan con '#'
# y se extienden hasta el final de la línea

#= Con '#=' y '=#' se pueden crear comentarios multilínea
   #= ¡Incluso se pueden anidar! =# :)
=#

## Variables y sentencias

In [2]:
# Aquí se crean unas cuantas variables
contador = 0
incremento = 1;
λ₀! = true       # Nombres unicode con símbolos
                 # (puede usarse LATEX, \lambda<TAB>\_0<TAB>)
const constante  # Constantes, aunque no son totalmente confiables
# Nótese que las sentencias pueden terminarse con ';' o no.
# Julia acepta una sentencia tan pronto la considere
# código válido, puede ser necesario utilizar paréntesis
auxiliar = true

true

In [ ]:
# Mal
correcto = auxiliar
         = false

In [ ]:
# Bien
correcto = (auxiliar = true)

In [3]:
A = [1,2,3]      # Array de 1 dimensión de tamaño 3
B = A            # Las asignaciones cambian el objeto al que
                 # se refiere una variable, no copian el objeto
B[1] = 10        # Los índices empiezan por 1, no por 0
A[1]

10

In [4]:
# Sin emabrgo, cuando asignas un valor primitivo,
# se comporta como si copiaras el valor
B = 1000       # Las variables no tienen tipo (por defecto), los datos sí
# ... pero se puede anotar el tipo de una variable.
C::Array{Int64} = A

3-element Vector{Int32}:
 10
  2
  3

In [5]:
C = B          # Tipos incompatibles

LoadError: MethodError: Cannot `convert` an object of type 
  Int32 to an object of type 
  Array{Int64}

Closest candidates are:
  convert(::Type{T}, ::AbstractArray) where T<:Array
   @ Base array.jl:665
  convert(::Type{T}, ::LinearAlgebra.AbstractQ) where T<:AbstractArray
   @ LinearAlgebra ~/.local/share/julia/stdlib/v1.10/LinearAlgebra/src/abstractq.jl:45
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray
   @ LinearAlgebra ~/.local/share/julia/stdlib/v1.10/LinearAlgebra/src/factorization.jl:108
  ...


## Tipos y literales

### Numéricos

In [19]:
# Los tipos numéricos tienen tamaño limitado por defecto
# Enteros con y sin signo desde 8 hasta 128 bits
i₁ = 1_000        # '_' para separar grupos de dígitos
i₂ = 0xcaffee     # Hexadecimal
i₃ = 0o777        # Octal
i₄ = 0b100101     # Binario
# Los literales de base distinta de 10 son sin signo
i₂ = -0x1         # Esto no es lo que parece

0xff

In [7]:
i₁ = 000123      # Los ceros a la izquierda no cuentan

123

In [8]:
i₃ = 0o000123    # ¿O sí?
# ¡Claro!  Cuando la base no es decimal

0x0053

In [9]:
# También hay punto flotante
# Desde 16 hasta 64 bits
f₁ = -1.6        # 64 bits
f₁ = .345e10     # También 64 bits
f₂ = 034.3f-1    # Se usa 'f' en lugar de 'e'
f₃ = 0x3f.3p2    # Flotante hexadecimal (64 bits), se usa 'p'
                 # y el exponente es de potencia base 2

252.75

In [9]:
# Valores de punto flotante especiales
f₁ = Inf         # Infinito
f₂ = -1/0        # -Inf
f₃ = NaN         # Not-a-Number
f₃ = 0/0

NaN

In [11]:
# Números de tamaño y precisión arbitrarios
# Tienen que especificarse como tal con antelación,
# no se convierten automáticamente cuando los cálculos
# se hacen irrepresentables.
i₁ = BigInt(0x1ff)
i₂ = big"1e1000"

1.000000000000000000000000000000000000000000000000000000000000000000000000000004e+1000

### Booleanos

In [15]:
# Los booleanos son un tipo de enteros.
# 'true' equivale a 1 y 'false' equivale a 0;
# además 'false' * cualquier_cosa == 0
if 1
    s = "pero sólo se permiten booleanos donde deba"
    s *= " haber una condición"
end

LoadError: TypeError: non-boolean (Int32) used in boolean context

### Cadenas

In [6]:
s = "se utilizan comillas dobles"
s = """pueden ser comillas dobles tres veces
para que pueda pasar varias líneas"""

"pueden ser comillas dobles tres veces\npara que pueda pasar varias líneas"

In [7]:
s = "esto no" "funciona"

LoadError: ParseError:
# Error @ ]8;;file:///home/catz/In[7]#1:14\In[7]:1:14]8;;\
s = "esto no" "funciona"
#            └─────────┘ ── extra tokens after end of expression

In [8]:
c = 'u'        # Las comillas simples son para un solo carácter
typeof(c)

Char

In [12]:
s = "Se puede usar \"escapes\" tipo \x43"

"Se puede usar \"escapes\" tipo C"

In [13]:
s = "Se puede usar dólar para insertar variables: $A"

"Se puede usar dólar para insertar variables: [10, 2, 3]"

### Arrays

In [14]:
# Los arrays pueden tener cualquier cantidad de dimensiones.
# Se pueden escribir literales para vectores y matrices.
A = [1, 2, 3]            # Se usan comas para separar filas.
A = [1,                  # Los elementos de los arrays se disponen
     2,                  # por columnas primero, el vector es
     3]                  # vector columna
B = [[1, 5, 3] [4, 2, 8]] # matriz, usa espacios para separar las columnas

3×2 Matrix{Int32}:
 1  4
 5  2
 3  8

### Tuplas

In [47]:
# A diferencia de los arrays, las tuplas son inmutables
# y generalmente están pensadas para contener valores heterogéneos
tupla = 1, 2, 3
tupla = (1, 4, 7)     # Los paréntesis son opcionales, excepto para
                      # una 0-tupla, y las 1-tupla requieren una ','
                      # al final.

(1, 4, 7)

In [48]:
tupla[1] = 20    # Error, no se puede modificar

LoadError: MethodError: no method matching setindex!(::Tuple{Int32, Int32, Int32}, ::Int32, ::Int32)

In [50]:
tupla = ([0, 1], 2, true)    # Pero sí redefinir
tupla[1][1] = 20             # Y los elementos pueden mutarse, aunque no
                             # reemplazarse por otros en la tupla
tupla

([20, 1], 2, true)

## Estructuras de selección y repetición

In [11]:
while true
    contador += incremento
    if contador ≥ 100       # Caracteres unicode para los operadores, puede ser >=
        break
    elseif contador == 50
        println("Pasó por 50...")
    end
end                         # Todo bloque de código termina con un 'end'

In [12]:
contador

100

In [10]:
# Rangos, son secuencias como en Python
inicio = 0
paso = 2
fin = 10
rango = inicio:paso:fin  # Nótese que el fin está incluido en el rango

0:2:10

In [13]:
s = ""
for i in rango           # Una iteración por cada elemento del iterable
    s *= string(i) * " "
end
s

"0 2 4 6 8 10 "

## Operadores

### Aritméticos

In [21]:
# Operadores aritméticos
i₁ = -i₂ * (i₃^2 % 20)      # '^' es exponenciación y '%' es residuo
i₁ / i₂ == i₂ \ i₁        # La barra invertida conmuta los operandos de división
                          # La división siempre es en punto flotante
i₁ = 21 ÷ 5               # '÷' es para la división entera (\div<TAB>)

4

In [24]:
# Operadores en bits
i₁ = i₂ & 0b01101001      # '&' para un 'and' bit a bit
i₁ = i₁ | 0b01101001      # '|' para un 'or' bit a bit
i₁ = ~i₁ ⊻ i₂             # '~' es negado y '⊻' (\xor) es 'xor'
# También se pueden usar las funciones 'nand', 'nor' y 'xor'
#                                       ⊼       ⊽       ⊻

0x69

In [25]:
# Más operadores en bits
i₁ = (1 << 5)      # Desplaza 1, 5 veces a la izquierda (2^5)
i₁ = (i₂ >> 5)     # Desplaza i₂, 5 veces a la derecha (i₂ ÷ 2^5)

0x07

In [26]:
# Operaciones en el sitio: modifican la variable original
i₁ += 100
i₂ |= 0xac
i₃ ^= 2
i₄ <<= 3

0x28

In [55]:
# Como caso especial, se pueden escribir literales numéricos
# justo antes de una variable para representar una
# multiplicación implícita
2i₄ - 3i₃ + 7i₁      # No se puede separar con espacio el número de la variable

-192710

### Comparativos

In [28]:
# Se pudedn combinar en una sola expresión, con un '&&'
# implícito uniendo cada par
cond = 2 < 3 != 5 >= 4 ≥ 4 ≤ 10 == 10 ≠ 0

true

In [29]:
# Ternario
s = cond ? "cierto" : "falso"

"cierto"

### Operaciones con tensores (arrays)

In [32]:
# Suma de vectores
A = [1, 2, 3];  B = [3, 2, 1]
A + B

3-element Vector{Int32}:
 4
 4
 4

In [39]:
# Producto de matrices
A = [    1.      2.      3.
         3.      4.      5.
         7.      6.      5.]
B = [-17/16     1/4    3/16
        3/2    -1/2      0 
      -5/16     1/4   -1/16]
A * B

3×3 Matrix{Float64}:
 1.0   0.0  0.0
 1.25  0.0  0.25
 0.0   0.0  1.0

### Operaciones vectorizadas

In [40]:
#=
 Se puede escribir un punto '.' justo antes de cualquier
 operador o justo después del nombre de cualquier función
 para hacer que opere elemento por elemento en los arrays,
 en lugar de sobre el array completo
=#
A .* B

3×3 Matrix{Float64}:
 -1.0625   0.5   0.5625
  4.5     -2.0   0.0
 -2.1875   1.5  -0.3125

In [41]:
A == B    # Comparación completa

false

In [42]:
A .== B   # Comparación elemento a elemento

3×3 BitMatrix:
 0  0  0
 0  0  0
 0  0  0

## Funciones

In [88]:
function una_funcion(x, y)
    c = x + y
    x^2 + c*x*y + y^2        # El valor devuelto por la función
end                          # es el de la última expresión evaluada

function otra_funcion(ρ, θ)
    return ρ * cos(θ), ρ * sin(θ)  # El 'return' es opcional aquí.
                                   # La función puede devolver varios
                                   # valores con una tupla
end

otra_funcion (generic function with 1 method)

In [44]:
# La llamada a la función debe tener los paréntesis
# unidos al nombre de la función...
una_funcion (2, 3)           # Esto no funciona

LoadError: ParseError:
# Error @ ]8;;file:///home/catz/In[44]#3:12\In[44]:3:12]8;;\
# unidos al nombre de la función...
una_funcion (2, 3)           # Esto no funciona
#          ╙ ── whitespace is not allowed here

In [45]:
una_funcion(2, 3)           # Esto sí funciona

43

In [51]:
# También se puede definir una función con una sintaxis de asignación
tercera_funcion(a, b, c) = a * b + c

tercera_funcion (generic function with 1 method)

In [52]:
# Y finalmente se puede usar una expresión tipo lambda
lambda = (x, y) -> (x + y) * (x - y)

#1 (generic function with 1 method)

In [56]:
# Una forma más de crear una función anónima es omitir el nombre
function ()
    "No estoy seguro aún para qué quiero ésta"
end

#3 (generic function with 1 method)

### Polimorfismo

In [67]:
#=
 Las funciones se pueden definir con valores por defecto
 para algunos parámetros (o todos), y si se le añaden
 anotaciones de tipo a los parámetros, se pueden "sobrecargar",
 o mejor dicho, se utiliza despacho múltiple, que determina
 la versión de la función a llamar basado en el tipo durante
 la ejecución de sus argumentos en una llamada particular.

 Las varias versiones de la función se llaman 'métodos' en Julia
=#

function norma(vector::Vector{<:Number}=[1, 1, 1])
    √(sum(x -> x^2, vector))
end

function norma(matriz::Matrix{<:Integer})
    maximum(x -> abs(x == typemin(typeof(x)) ? BigInt(x) : x), matriz)
end

function norma(matriz::Matrix{<:AbstractFloat})
    maximum(abs, matriz)
end

# Nótese cómo se pasaron funciones como argumentos a otra función;
# en Julia, las funciones son objetos llamables, que se pueden
# pasar ida y vuelta hacia/desde otras funciones.

norma (generic function with 7 methods)

In [68]:
println("Norma sin parámetros: $(norma())")
println("Norma con vector: $(norma([2, 1, 2]))")
println("Norma con matriz: $(norma(A))")

Norma sin parámetros: 1.7320508075688772
Norma con vector: 3.0
Norma con matriz: 7.0


In [78]:
# También se pueden crear funciones con argumentos no posicionales,
# sino de palabra clave.  Estos no se pueden pasar por posición,
# sólo por el nombre.

clave(; laclave1, laclave2, laclave3=0) = println("clave con 2 o 3 argumentos")

clave (generic function with 1 method)

In [79]:
clave()  # Error, falta el argumento de palabra clave

LoadError: UndefKeywordError: keyword argument `laclave1` not assigned

In [81]:
clave(0, 1)  # Error, no se puede pasar los parámetros por posición

LoadError: MethodError: no method matching clave(::Int32, ::Int32)

In [82]:
clave(laclave1=1, laclave2=2)
clave(laclave1=1, laclave2=2, laclave3=3)

clave con 2 o 3 argumentos
clave con 2 o 3 argumentos


### Extras

In [86]:
# Para pasar funciones anónimas grandes a funciones de orden superior
# hay una sintaxis alternativa más cómoda para pasar la función
# anónima como primer argumento, quitandolo de la llamada normal.

println(A)

maximum(A) do elem     # La lista de parámetros va luego del 'do'
    elem = abs2(elem)
    if elem > 25
        elem ÷= 2
    end
    return elem
end

[1.0 2.0 3.0; 3.0 4.0 5.0; 7.0 6.0 5.0]


25.0

In [98]:
# Composición de funciones, forma matemática
norma_euclidiana = (sqrt ∘ sum ∘ (x -> x.^2))
println(norma_euclidiana([1, 2, 3, 4, 5, 6]))

# forma de tuberías
[1, 2, 3, 4, 5, 6] |> x -> x.^2 |> sum |> sqrt |> println

9.539392014169456
9.539392014169456


## Estructuras (clases sin métodos)

In [103]:
#=
 El sistema de tipos de Julia permite crear tipos abstractos
 y tipos concretos.  Los abstractos no contienen campos de datos,
 no se pueden instanciar, pero se pueden derivar (o subtipar);
 mientras que los concretos tienen campos de datos y se pueden
 instanciar, pero no se pueden derivar.
=#

abstract type Vehículo end       # 'Con acento'
struct Carro <: Vehículo         # 'Carro' deriva de 'Vehículo'
    velocidad::Real              # Campo (o propiedad, atributo) con tipo
    color                        # Campo de cualquier tipo (tipo Any)
    peso::Integer                # Un tanto arbitrario
end

a::Vehículo = Carro(24.0, "azul", 200)
println(a)
println(a.color)

Carro(24.0, "azul", 200)
azul


In [104]:
a.color = "verde"         # No se pueden modificar los campos por defecto

LoadError: setfield!: immutable struct of type Carro cannot be changed

In [105]:
mutable struct Moto <: Vehículo       # Hay que declararlo 'mutable'
    velocidad::Real
    color
    peso::Integer
end

a = Moto(15, "verde", 50)
println(a)
println(a.color)
a.color = "rojo"

Moto(15, "verde", 50)
verde


"rojo"